# Generated by Django 2.2 on 2019-04-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieShop', '0003_auto_20190430_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
