# Generated by Django 2.2 on 2019-04-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_postal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-nazwisko',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='adres',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='miasto',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='nazwisko',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='zaplacone',
        ),
    ]
