# Generated by Django 2.2 on 2019-04-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190430_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-last_name',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='miasto',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='imie',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='nazwisko',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zaplacone',
            new_name='paid',
        ),
    ]
